### ISSUE TITLE
cannot install ribbon

### ISSUE THREAD

**Issue by simonm3** [xlwings/xlwings#805]
I have done xlwings addin remove; xlwings addin install. I have copied the xlam file to XLSTART.  But I still see no ribbon.

**Comment by fzumstein** [comment]
download xlwings.xlam from https://github.com/ZoomerAnalytics/xlwings/releases and install manually, see also here: https://training.zoomeranalytics.com/courses/xlwings/lectures/4231276

**Comment by simonm3** [comment]
Thanks. Note that pip installs 11.6 but uses the 11.5 version of the xlam
file.

I now have a ribbon. However it says file not found xlwings32.dll 53. Is
there some other path setting I have to make? Not mentioned on the video
link.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by simonm3** [comment]
OK it turns out the xlwings32.dll was in C:/anaconda3/xlwings32-0.11.6.dll.
I just renamed it xlwings32.dll and it now works.

**Comment by fzumstein** [comment]
sorry, I accidentally uploaded the wrong version to the GitHub release page. It's fixed now. So instead of renaming the dll you should replace the excel addin with the correct version now.

**Comment by simonm3** [comment]
For some reason it stopped working. I reinstalled again and no toolbar. If I use the xlam file on github then the toolbar now appears. This is a 62K file versus the 47K file on latest release.

However I still can't actually run anything because it says "Runtime error 53. File not found xlwings32.dll". I renamed the file as before but still not working. Have checked the path and even copied it to windows/system32.

**Comment by fzumstein** [comment]
try to reinstall everything from scratch. things to double check that everything is correctly installed: 

* ribbon needs to show the correct version number, i.e. 0.11.7 for latest release
* the dlls are versioned since release 0.11.5, i.e. need to be called `xlwings32-0.11.7.dll` for 0.11.7
* make sure you also get that version number when doing `import xlwings` and `xlwings.__version__`

**Comment by simonm3** [comment]
Got it working but....After reinstall the ribbon does not appear until I copy the 63K XLAM file. The DLL is still missing until I rename it to xlwings32.dll. Seems like incorrect xlam file on last release. And for some reason it is not finding the DLL with release name on the end.

**Comment by fzumstein** [comment]
I can't replicate the issues for the 0.11.7 release, I've checked the file on PyPI and also the xlam on GH and all have the version correctly on the addin and dll side...

**Comment by simonm3** [comment]
Odd. I am on windows10, office 2007, anaconda python3. The xlam file that
works is the 63K one versus the release one which is smaller.

**Comment by fzumstein** [comment]
not sure where that file size gets messed up but it's definitely the same on GH release page for 0.11.7 as in the PyPI packge, check size here: https://github.com/ZoomerAnalytics/xlwings/releases do you use the pip or conda package?

**Comment by simonm3** [comment]
pip

**Comment by fzumstein** [comment]
the source version doesn't have the version tags (they get added during build). so it still looks for the dlls that you had renamed (but you shouldn't have).

**Comment by simonm3** [comment]
Ah that explains that. So is it just wrong version on the release?
Presumably the source version (the one that works) is the latest.

**Comment by fzumstein** [comment]
0.11.6 was initially wrong but then I uploaded the correct version to the release page. 0.11.7 should be correct throughout.

**Comment by simonm3** [comment]
This one is 62K (and works)

https://github.com/ZoomerAnalytics/xlwings/blob/master/xlwings/addin/xlwings.xlam

This page is 46K. And it is the same file on pypi

https://github.com/ZoomerAnalytics/xlwings/releases

**Comment by jkbgbr** [comment]
First time xlwings installer here with the same issue.
The .xlam file available at the 0.11.7 release (ca. 47 kB) does not work. However in the zip there is a larger one that seems to work just fine (the addin shows in the ribbon). Thanks for the tip, @simonm3 !
The following worked for me using conda, would probably work using pip as well. The problem seems to be .xlam file that comes when using  package manager.
- install xlwings (pip or conda)
- download the zip from the github release page, extract and get the .xlam file  from \xlwings-0.11.7\xlwings\addin
- overwrite the xlam in the directory where xlwings was just installed to \Lib\site-packages\xlwings\addin
- run the addin install from within the environment
- start excel, enjoy.

**Comment by fzumstein** [comment]
Whatever goes wrong on your end, this workaround is very very wrong. The zip file contains a template which can only work correctly if you are on an old version of the xlwings dlls. I don't mind to look into that issue on your end using something like TeamViewer, please ping me (email on my profile page).
